context:
  version: "0.14.1"

package:
  name: tea
  version: ${{ version }}

source:
  - url: https://gitea.com/gitea/tea/archive/v${{ version }}.tar.gz
    sha256: 848b6b2fafa270fa77b4e278d521bfcc16d2f721c45ac90f08f5b16dc630c3f9
    target_directory: src
  - url: https://github.com/go-authgate/authgate/raw/main/LICENSE
    sha256: 16d8778aef2c07d03e50c7933b3ce7af60652d59ba5a30a4f978b6cabe8dcf60
    target_directory: go-authgate-sdk-go-license
    file_name: LICENSE
  - url: https://raw.githubusercontent.com/alecthomas/chroma/refs/heads/master/COPYING
    sha256: 13654b052f885cb3fa47d7343e13975d9c8a64c3bcd84993c35d5eb01f22b23f
    target_directory: alecthomas-chroma
    file_name: COPYING
  - if: win
    then:
      url: https://github.com/mattn/go-localereader/raw/master/LICENSE
      sha256: dceede03550621e65ec7b79fcba87cf6dbb9d31132a8ae71a8fe8ceec0af7da3
      target_directory: go-localereader-license
      file_name: LICENSE

build:
  number: 0
  script:
    - cd src
    - go-licenses save . --save_path ../library_licenses --ignore github.com/go-authgate/sdk-go/credstore --ignore github.com/alecthomas/chroma ${{ "--ignore github.com/mattn/go-localereader" if win }}
    - if: win
      then:
        - mkdir ..\library_licenses\github.com\mattn\go-localereader
        - copy ..\go-localereader-license\LICENSE ..\library_licenses\github.com\mattn\go-localereader\LICENSE
    - if: unix
      then: go build -v -o $PREFIX/bin/tea -ldflags="-s -w"
      else: go build -v -o %LIBRARY_BIN%\tea.exe -ldflags="-s"

requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - go-licenses

tests:
  - script:
      - tea --version
  - package_contents:
      bin:
        - tea
      strict: true

about:
  homepage: https://gitea.com/gitea/tea
  summary: A command line tool to interact with Gitea servers
  description: |
    tea is the official CLI for Gitea. It can be used to manage and
    interact with Gitea servers from the command line.
  license: MIT
  license_file:
    - src/LICENSE
    - library_licenses/
    - go-authgate-sdk-go-license/LICENSE
    - alecthomas-chroma/COPYING
  documentation: https://gitea.com/gitea/tea
  repository: https://gitea.com/gitea/tea

extra:
  recipe-maintainers:
    - pavelzw
